/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import { a, useSpring } from "@react-spring/three"

export default function Model2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/comoda_ludmila_clean.glb")
  const { actions } = useAnimations(animations, group)

  const [hovered, setHovered] = useState(false)
  const [animate, setAnimate] = useState(false)

  const { color } = useSpring({ color: hovered ? "hotpink" : "white" })
  useEffect(() => void (document.body.style.cursor = hovered ? "pointer" : "auto"), [hovered])
  useEffect(() => {
    animate ? (actions["PortaTrack"].play().loop = false) : actions["PortaTrack"].stop()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="COMODA" position={[0.5486, 0.5496, -0.0079]} rotation={[Math.PI / 2, 0, 0]}>
          <group name="PORTA" position={[-0.0125, 0.1998, -0.2781]}>
            <group name="NAUO45" position={[-0.0141, -0.0114, -0.0009]} rotation={[-Math.PI, 0, -1.6829]}>
              <mesh
                name="NAUO48"
                castShadow
                receiveShadow
                geometry={nodes.NAUO48.geometry}
                material={nodes.NAUO48.material}
                position={[0.0057, -0.006, 0]}
                rotation={[-Math.PI / 2, -1.4125, 0]}
              />
            </group>
            <group name="NAUO46" position={[-0.0141, -0.0114, 0.5831]} rotation={[Math.PI, 0, -1.6829]}>
              <mesh
                name="NAUO48001"
                castShadow
                receiveShadow
                geometry={nodes.NAUO48001.geometry}
                material={nodes.NAUO48001.material}
                position={[0.0057, -0.006, 0]}
                rotation={[-Math.PI / 2, -1.4125, 0]}
              />
            </group>
            <group
              name="PORTA_MESH"
              position={[0.0028, -0.0076, 0.2911]}
              onPointerOver={() => setHovered(true)}
              onPointerOut={() => setHovered(false)}
              onClick={() => setAnimate(!animate)}>
              <a.mesh
                name="23381_-_PORTA_LUDMILA_-_ISISN-_L̇IA001"
                castShadow
                receiveShadow
                geometry={nodes["23381_-_PORTA_LUDMILA_-_ISISN-_L̇IA001"].geometry}
                material={nodes["23381_-_PORTA_LUDMILA_-_ISISN-_L̇IA001"].material}
                color={color}
              />
              <mesh
                name="23381_-_PORTA_LUDMILA_-_ISISN-_L̇IA001_1"
                castShadow
                receiveShadow
                geometry={nodes["23381_-_PORTA_LUDMILA_-_ISISN-_L̇IA001_1"].geometry}
                material={nodes["23381_-_PORTA_LUDMILA_-_ISISN-_L̇IA001_1"].material}
              />
              <mesh
                name="23381_-_PORTA_LUDMILA_-_ISISN-_L̇IA001_2"
                castShadow
                receiveShadow
                geometry={nodes["23381_-_PORTA_LUDMILA_-_ISISN-_L̇IA001_2"].geometry}
                material={nodes["23381_-_PORTA_LUDMILA_-_ISISN-_L̇IA001_2"].material}
              />
              <mesh
                name="23381_-_PORTA_LUDMILA_-_ISISN-_L̇IA001_3"
                castShadow
                receiveShadow
                geometry={nodes["23381_-_PORTA_LUDMILA_-_ISISN-_L̇IA001_3"].geometry}
                material={nodes["23381_-_PORTA_LUDMILA_-_ISISN-_L̇IA001_3"].material}
              />
            </group>
          </group>
          <group name="GAVETA1" position={[-1.1477, -0.2438, 0.6452]}>
            <group name="GAVETA1_MESH" position={[0.4061, 0.4413, -0.3546]}>
              <mesh name="GAV1" castShadow receiveShadow geometry={nodes.GAV1.geometry} material={nodes.GAV1.material} />
              <mesh name="GAV1_1" castShadow receiveShadow geometry={nodes.GAV1_1.geometry} material={nodes.GAV1_1.material} />
              <mesh name="GAV1_2" castShadow receiveShadow geometry={nodes.GAV1_2.geometry} material={nodes.GAV1_2.material} />
            </group>
          </group>
          <group name="GAVETA2" position={[-1.1477, -0.2438, 0.4602]}>
            <group name="GAVETA2_MESH" position={[0.4061, 0.4413, -0.3546]}>
              <mesh name="GAV2" castShadow receiveShadow geometry={nodes.GAV2.geometry} material={nodes.GAV2.material} />
              <mesh name="GAV2_1" castShadow receiveShadow geometry={nodes.GAV2_1.geometry} material={nodes.GAV2_1.material} />
              <mesh name="GAV2_2" castShadow receiveShadow geometry={nodes.GAV2_2.geometry} material={nodes.GAV2_2.material} />
            </group>
          </group>
          <group name="GAVETA3" position={[-1.1477, -0.2438, 0.2752]}>
            <group name="GAVETA3_MESH" position={[0.4061, 0.4413, -0.3546]}>
              <mesh name="GAV3" castShadow receiveShadow geometry={nodes.GAV3.geometry} material={nodes.GAV3.material} />
              <mesh name="GAV3_1" castShadow receiveShadow geometry={nodes.GAV3_1.geometry} material={nodes.GAV3_1.material} />
              <mesh name="GAV3_2" castShadow receiveShadow geometry={nodes.GAV3_2.geometry} material={nodes.GAV3_2.material} />
            </group>
          </group>
          <group name="GAVETA4" position={[-1.1477, -0.2438, 0.0902]}>
            <group name="GAVETA4_MESH" position={[0.4061, 0.4413, -0.3546]}>
              <mesh name="GAV4" castShadow receiveShadow geometry={nodes.GAV4.geometry} material={nodes.GAV4.material} />
              <mesh name="GAV4_1" castShadow receiveShadow geometry={nodes.GAV4_1.geometry} material={nodes.GAV4_1.material} />
              <mesh name="GAV4_2" castShadow receiveShadow geometry={nodes.GAV4_2.geometry} material={nodes.GAV4_2.material} />
            </group>
          </group>
          <mesh
            name="PINOS_AJUSTE"
            castShadow
            receiveShadow
            geometry={nodes.PINOS_AJUSTE.geometry}
            material={nodes.PINOS_AJUSTE.material}
            position={[-0.0169, 0.08, 0.1256]}
            rotation={[-1.2566, 0, Math.PI / 2]}
          />
          <group name="CORPO" position={[-0.5584, 0.0085, 0.3911]}>
            <mesh
              name="22625_-_TAMPO_BASE001"
              castShadow
              receiveShadow
              geometry={nodes["22625_-_TAMPO_BASE001"].geometry}
              material={nodes["22625_-_TAMPO_BASE001"].material}
            />
            <mesh
              name="22625_-_TAMPO_BASE001_1"
              castShadow
              receiveShadow
              geometry={nodes["22625_-_TAMPO_BASE001_1"].geometry}
              material={nodes["22625_-_TAMPO_BASE001_1"].material}
            />
            <mesh
              name="22625_-_TAMPO_BASE001_2"
              castShadow
              receiveShadow
              geometry={nodes["22625_-_TAMPO_BASE001_2"].geometry}
              material={materials["mat_2.001"]}
            />
            <mesh
              name="22625_-_TAMPO_BASE001_3"
              castShadow
              receiveShadow
              geometry={nodes["22625_-_TAMPO_BASE001_3"].geometry}
              material={nodes["22625_-_TAMPO_BASE001_3"].material}
            />
            <mesh
              name="22625_-_TAMPO_BASE001_4"
              castShadow
              receiveShadow
              geometry={nodes["22625_-_TAMPO_BASE001_4"].geometry}
              material={nodes["22625_-_TAMPO_BASE001_4"].material}
            />
          </group>
          <mesh
            name="PES"
            castShadow
            receiveShadow
            geometry={nodes.PES.geometry}
            material={nodes.PES.material}
            position={[-0.4384, 0.0085, 0.3986]}
            rotation={[Math.PI, 0, 0.9225]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/comoda_ludmila_clean.glb")
